credentials:
  TRAVIAN_EMAIL: your.email@example.com
  TRAVIAN_PASSWORD: your-password-here
  TRAVIAN_X_VERSION: ''

core_profile:
  SERVER_SELECTION: 0
  WAIT_BETWEEN_CYCLES_MINUTES: 5
  JITTER_MINUTES: 5
  SKIP_CYCLE_PROB: 0.0
  TRIBE_HINT: ''
  ESCORT_UNIT_PRIORITY:
    - t5
    - t3
    - t1
    - t2
    - t4
    - t6
    - t7
    - t8
    - t9
    - t10

limiter:
  ENABLE_CYCLE_LIMITER: false
  DAILY_MAX_RUNTIME_MINUTES: 600
  DAILY_BLOCKS: 3
  DAILY_VARIANCE_PCT: 0.0
  BLOCK_SIZE_MIN: 45
  BLOCK_SIZE_MAX: 200
  REST_MIN_MINUTES: 30
  REST_MAX_MINUTES: 90
  QUIET_WINDOWS:
    - "01:00-06:00"
  QUIET_WINDOW_RESUME_JITTER_MIN: 90
  QUIET_WINDOW_RESUME_JITTER_MAX: 300

logging:
  LOG_LEVEL: INFO
  LOG_DIR: logs

humanizer:
  HUMAN_MIN_DELAY: 0.6
  HUMAN_MAX_DELAY: 2.2
  HUMAN_LONG_PAUSE_EVERY: 7
  HUMAN_LONG_PAUSE_MIN: 3.0
  HUMAN_LONG_PAUSE_MAX: 6.0
  HUMAN_IDLE_LOOKAROUND_PROB: 0.25
  HUMAN_IDLE_MIN_INTERVAL: 45
  HUMAN_IDLE_MAX_INTERVAL: 180
  HUMAN_IDLE_JITTER_MIN: 0.4
  HUMAN_IDLE_JITTER_MAX: 1.3
  HUMAN_SUSPICION_SLEEP_MIN: 90
  HUMAN_SUSPICION_SLEEP_MAX: 240
  HUMAN_IDLE_LOOKAROUND_PAGES: []

operation:
  OP_JITTER_MIN_SEC: 0.5
  OP_JITTER_MAX_SEC: 2.0
  OP_COFFEE_BREAK_PROB: 0.1
  OP_COFFEE_BREAK_MIN_MINUTES: 2
  OP_COFFEE_BREAK_MAX_MINUTES: 6

map_and_farms:
  MAPVIEW_PRE_ACTION_PROB: 0.35
  MAPVIEW_FARM_LIST_PROB: 0.25
  FARM_LIST_SUBSET_MIN: 1
  FARM_LIST_SUBSET_MAX: 3
  SHUFFLE_VILLAGE_ORDER: true
  FARM_LIST_RANDOM_SKIP_PROB: 0.15

raiding:
  EMPTY_OASIS_RAIDER_ENABLE: true
  HERO_OASIS_CLEAR_ENABLE: true
  FARM_LIST_RAIDER_ENABLE: true
  OASIS_EVENT_DRIVEN_WAIT_ENABLE: true
  SKIP_FARM_LISTS_FIRST_RUN: false

NEW_VILLAGE_PRESET_ENABLE: false

learning:
  LEARNING_ENABLE: true
  LEARNING_MIN_MUL: 0.8
  LEARNING_MAX_MUL: 2.5
  LEARNING_LOSS_THRESHOLD_LOW: 0.2
  LEARNING_LOSS_THRESHOLD_HIGH: 0.5
  LEARNING_STEP_UP_ON_LOST: 0.25
  LEARNING_STEP_UP_ON_HIGH_LOSS: 0.1
  LEARNING_STEP_UP_ON_FULL_LOOT: 1.0
  LEARNING_PAUSE_ON_LOSS_SEC: 3600
  LEARNING_PRIORITY_RETRY_SEC: 300
  PROCESS_RALLY_RETURNS: true
  RALLY_MATCH_TOLERANCE_SEC: 120
  RALLY_RETURN_TIMEOUT_SEC: 900

attack_detector:
  ATTACK_DETECTOR_ENABLE: false
  ATTACK_DETECTOR_DISCORD_WEBHOOK: ''
  ATTACK_DETECTOR_INTERVAL_BASE: 2.0
  ATTACK_DETECTOR_INTERVAL_JITTER: 6.0
  ATTACK_DETECTOR_COOLDOWN_SEC: 3600
  ATTACK_DETECTOR_OCR_LANGS:
    - en
  ATTACK_DETECTOR_GPU: false
  ATTACK_DETECTOR_SEND_SCREENSHOT: true
  ATTACK_DETECTOR_USE_HOTKEYS: false
  ATTACK_DETECTOR_REFRESH_COMBO: ''

hero_adventures:
  HERO_ADVENTURE_ENABLE: true
  HERO_ADVENTURE_MIN_HEALTH: 40
  HERO_ADVENTURE_MAX_DURATION_MIN: 180
  HERO_ADVENTURE_ALLOW_DANGER: true
  HERO_ADVENTURE_POLL_INTERVAL_SEC: 90
  HERO_ADVENTURE_RANDOM_JITTER_SEC: 45

progressive_tasks:
  PROGRESSIVE_TASKS_ENABLE: false
  PROGRESSIVE_TASKS_REFRESH_HUD: true

oasis_scheduler:
  OASIS_TARGET_INTERVAL_MIN_SEC: 600
  OASIS_INTERVAL_JITTER_SEC: 60
  OASIS_COOLDOWN_ON_LOST_SEC: 1800
  OASIS_EARLY_EXIT_IF_INSUFFICIENT: true
  OASIS_MAX_INSUFFICIENT_SKIPS: 10
  OASIS_ALWAYS_NEAREST_ONLY: false

building_guard:
  BUILD_GUARD_ENABLE: true
  BUILD_GUARD_MAX_RETRIES: 5
  BUILD_GUARD_WAIT_MIN_SEC: 60
  BUILD_GUARD_WAIT_MAX_SEC: 180
  BUILD_FREECROP_GUARD_ENABLE: true
  BUILD_STORAGE_GUARD_ENABLE: true

resource_balancer:
  RESOURCE_FIELD_BALANCER_ENABLE: false
  RESOURCE_FIELD_BALANCER_INCLUDE_GRAIN: true
